[package]
name = "rwc"
version = "0.1.0"
authors = ["Adrien Fabre <adrien.fabre@dashlane.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
